name: gh pages, react client-side routing

on:
  push:
    branches:
      - master

jobs:
  build-deploy-gh-pages:
    name: Build / Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Install dependencies (custom)
        run: |
          yarn add @easyops-cn/docusaurus-search-local
      - name: Build
        run: |
          yarn build
      - name: Deploy Frontend to gh pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: website/build
